---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-applicationautoscaling-writer
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - applicationautoscaling.services.k8s.aws
  resources:
  - scalabletargets

  - scalingpolicies

  - scheduledactions

  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - applicationautoscaling.services.k8s.aws
  resources:
  - scalabletargets
  - scalingpolicies
  - scheduledactions
  verbs:
  - get
  - patch
  - update
