// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package scaling_policy

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/applicationautoscaling"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/applicationautoscaling/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/applicationautoscaling-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ScalingPolicy{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	rm.customSetDescribeScalingPoliciesInput(ctx, r, input)
	var resp *svcsdk.DescribeScalingPoliciesOutput
	resp, err = rm.sdkapi.DescribeScalingPolicies(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeScalingPolicies", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ScalingPolicies {
		if elem.Alarms != nil {
			f0 := []*svcapitypes.Alarm{}
			for _, f0iter := range elem.Alarms {
				f0elem := &svcapitypes.Alarm{}
				if f0iter.AlarmARN != nil {
					f0elem.AlarmARN = f0iter.AlarmARN
				}
				if f0iter.AlarmName != nil {
					f0elem.AlarmName = f0iter.AlarmName
				}
				f0 = append(f0, f0elem)
			}
			ko.Status.Alarms = f0
		} else {
			ko.Status.Alarms = nil
		}
		if elem.CreationTime != nil {
			ko.Status.CreationTime = &metav1.Time{*elem.CreationTime}
		} else {
			ko.Status.CreationTime = nil
		}
		if elem.PolicyARN != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.PolicyARN)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.PolicyName != nil {
			ko.Spec.PolicyName = elem.PolicyName
		} else {
			ko.Spec.PolicyName = nil
		}
		if elem.PolicyType != "" {
			ko.Spec.PolicyType = aws.String(string(elem.PolicyType))
		} else {
			ko.Spec.PolicyType = nil
		}
		if elem.ResourceId != nil {
			ko.Spec.ResourceID = elem.ResourceId
		} else {
			ko.Spec.ResourceID = nil
		}
		if elem.ScalableDimension != "" {
			ko.Spec.ScalableDimension = aws.String(string(elem.ScalableDimension))
		} else {
			ko.Spec.ScalableDimension = nil
		}
		if elem.ServiceNamespace != "" {
			ko.Spec.ServiceNamespace = aws.String(string(elem.ServiceNamespace))
		} else {
			ko.Spec.ServiceNamespace = nil
		}
		if elem.StepScalingPolicyConfiguration != nil {
			f9 := &svcapitypes.StepScalingPolicyConfiguration{}
			if elem.StepScalingPolicyConfiguration.AdjustmentType != "" {
				f9.AdjustmentType = aws.String(string(elem.StepScalingPolicyConfiguration.AdjustmentType))
			}
			if elem.StepScalingPolicyConfiguration.Cooldown != nil {
				cooldownCopy := int64(*elem.StepScalingPolicyConfiguration.Cooldown)
				f9.Cooldown = &cooldownCopy
			}
			if elem.StepScalingPolicyConfiguration.MetricAggregationType != "" {
				f9.MetricAggregationType = aws.String(string(elem.StepScalingPolicyConfiguration.MetricAggregationType))
			}
			if elem.StepScalingPolicyConfiguration.MinAdjustmentMagnitude != nil {
				minAdjustmentMagnitudeCopy := int64(*elem.StepScalingPolicyConfiguration.MinAdjustmentMagnitude)
				f9.MinAdjustmentMagnitude = &minAdjustmentMagnitudeCopy
			}
			if elem.StepScalingPolicyConfiguration.StepAdjustments != nil {
				f9f4 := []*svcapitypes.StepAdjustment{}
				for _, f9f4iter := range elem.StepScalingPolicyConfiguration.StepAdjustments {
					f9f4elem := &svcapitypes.StepAdjustment{}
					if f9f4iter.MetricIntervalLowerBound != nil {
						f9f4elem.MetricIntervalLowerBound = f9f4iter.MetricIntervalLowerBound
					}
					if f9f4iter.MetricIntervalUpperBound != nil {
						f9f4elem.MetricIntervalUpperBound = f9f4iter.MetricIntervalUpperBound
					}
					if f9f4iter.ScalingAdjustment != nil {
						scalingAdjustmentCopy := int64(*f9f4iter.ScalingAdjustment)
						f9f4elem.ScalingAdjustment = &scalingAdjustmentCopy
					}
					f9f4 = append(f9f4, f9f4elem)
				}
				f9.StepAdjustments = f9f4
			}
			ko.Spec.StepScalingPolicyConfiguration = f9
		} else {
			ko.Spec.StepScalingPolicyConfiguration = nil
		}
		if elem.TargetTrackingScalingPolicyConfiguration != nil {
			f10 := &svcapitypes.TargetTrackingScalingPolicyConfiguration{}
			if elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification != nil {
				f10f0 := &svcapitypes.CustomizedMetricSpecification{}
				if elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Dimensions != nil {
					f10f0f0 := []*svcapitypes.MetricDimension{}
					for _, f10f0f0iter := range elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Dimensions {
						f10f0f0elem := &svcapitypes.MetricDimension{}
						if f10f0f0iter.Name != nil {
							f10f0f0elem.Name = f10f0f0iter.Name
						}
						if f10f0f0iter.Value != nil {
							f10f0f0elem.Value = f10f0f0iter.Value
						}
						f10f0f0 = append(f10f0f0, f10f0f0elem)
					}
					f10f0.Dimensions = f10f0f0
				}
				if elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.MetricName != nil {
					f10f0.MetricName = elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.MetricName
				}
				if elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Namespace != nil {
					f10f0.Namespace = elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Namespace
				}
				if elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Statistic != "" {
					f10f0.Statistic = aws.String(string(elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Statistic))
				}
				if elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Unit != nil {
					f10f0.Unit = elem.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Unit
				}
				f10.CustomizedMetricSpecification = f10f0
			}
			if elem.TargetTrackingScalingPolicyConfiguration.DisableScaleIn != nil {
				f10.DisableScaleIn = elem.TargetTrackingScalingPolicyConfiguration.DisableScaleIn
			}
			if elem.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification != nil {
				f10f2 := &svcapitypes.PredefinedMetricSpecification{}
				if elem.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.PredefinedMetricType != "" {
					f10f2.PredefinedMetricType = aws.String(string(elem.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.PredefinedMetricType))
				}
				if elem.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.ResourceLabel != nil {
					f10f2.ResourceLabel = elem.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.ResourceLabel
				}
				f10.PredefinedMetricSpecification = f10f2
			}
			if elem.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown != nil {
				scaleInCooldownCopy := int64(*elem.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown)
				f10.ScaleInCooldown = &scaleInCooldownCopy
			}
			if elem.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown != nil {
				scaleOutCooldownCopy := int64(*elem.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown)
				f10.ScaleOutCooldown = &scaleOutCooldownCopy
			}
			if elem.TargetTrackingScalingPolicyConfiguration.TargetValue != nil {
				f10.TargetValue = elem.TargetTrackingScalingPolicyConfiguration.TargetValue
			}
			ko.Spec.TargetTrackingScalingPolicyConfiguration = f10
		} else {
			ko.Spec.TargetTrackingScalingPolicyConfiguration = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	rm.customSetLastModifiedTimeToCreationTime(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return rm.customCheckRequiredFieldsMissing(r)
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeScalingPoliciesInput, error) {
	res := &svcsdk.DescribeScalingPoliciesInput{}

	if r.ko.Spec.ResourceID != nil {
		res.ResourceId = r.ko.Spec.ResourceID
	}
	if r.ko.Spec.ScalableDimension != nil {
		res.ScalableDimension = svcsdktypes.ScalableDimension(*r.ko.Spec.ScalableDimension)
	}
	if r.ko.Spec.ServiceNamespace != nil {
		res.ServiceNamespace = svcsdktypes.ServiceNamespace(*r.ko.Spec.ServiceNamespace)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutScalingPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.PutScalingPolicy(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "PutScalingPolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Alarms != nil {
		f0 := []*svcapitypes.Alarm{}
		for _, f0iter := range resp.Alarms {
			f0elem := &svcapitypes.Alarm{}
			if f0iter.AlarmARN != nil {
				f0elem.AlarmARN = f0iter.AlarmARN
			}
			if f0iter.AlarmName != nil {
				f0elem.AlarmName = f0iter.AlarmName
			}
			f0 = append(f0, f0elem)
		}
		ko.Status.Alarms = f0
	} else {
		ko.Status.Alarms = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.PolicyARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.PolicyARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.PutScalingPolicyInput, error) {
	res := &svcsdk.PutScalingPolicyInput{}

	if r.ko.Spec.PolicyName != nil {
		res.PolicyName = r.ko.Spec.PolicyName
	}
	if r.ko.Spec.PolicyType != nil {
		res.PolicyType = svcsdktypes.PolicyType(*r.ko.Spec.PolicyType)
	}
	if r.ko.Spec.ResourceID != nil {
		res.ResourceId = r.ko.Spec.ResourceID
	}
	if r.ko.Spec.ScalableDimension != nil {
		res.ScalableDimension = svcsdktypes.ScalableDimension(*r.ko.Spec.ScalableDimension)
	}
	if r.ko.Spec.ServiceNamespace != nil {
		res.ServiceNamespace = svcsdktypes.ServiceNamespace(*r.ko.Spec.ServiceNamespace)
	}
	if r.ko.Spec.StepScalingPolicyConfiguration != nil {
		f5 := &svcsdktypes.StepScalingPolicyConfiguration{}
		if r.ko.Spec.StepScalingPolicyConfiguration.AdjustmentType != nil {
			f5.AdjustmentType = svcsdktypes.AdjustmentType(*r.ko.Spec.StepScalingPolicyConfiguration.AdjustmentType)
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.Cooldown != nil {
			cooldownCopy0 := *r.ko.Spec.StepScalingPolicyConfiguration.Cooldown
			if cooldownCopy0 > math.MaxInt32 || cooldownCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field Cooldown is of type int32")
			}
			cooldownCopy := int32(cooldownCopy0)
			f5.Cooldown = &cooldownCopy
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.MetricAggregationType != nil {
			f5.MetricAggregationType = svcsdktypes.MetricAggregationType(*r.ko.Spec.StepScalingPolicyConfiguration.MetricAggregationType)
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.MinAdjustmentMagnitude != nil {
			minAdjustmentMagnitudeCopy0 := *r.ko.Spec.StepScalingPolicyConfiguration.MinAdjustmentMagnitude
			if minAdjustmentMagnitudeCopy0 > math.MaxInt32 || minAdjustmentMagnitudeCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field MinAdjustmentMagnitude is of type int32")
			}
			minAdjustmentMagnitudeCopy := int32(minAdjustmentMagnitudeCopy0)
			f5.MinAdjustmentMagnitude = &minAdjustmentMagnitudeCopy
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.StepAdjustments != nil {
			f5f4 := []svcsdktypes.StepAdjustment{}
			for _, f5f4iter := range r.ko.Spec.StepScalingPolicyConfiguration.StepAdjustments {
				f5f4elem := &svcsdktypes.StepAdjustment{}
				if f5f4iter.MetricIntervalLowerBound != nil {
					f5f4elem.MetricIntervalLowerBound = f5f4iter.MetricIntervalLowerBound
				}
				if f5f4iter.MetricIntervalUpperBound != nil {
					f5f4elem.MetricIntervalUpperBound = f5f4iter.MetricIntervalUpperBound
				}
				if f5f4iter.ScalingAdjustment != nil {
					scalingAdjustmentCopy0 := *f5f4iter.ScalingAdjustment
					if scalingAdjustmentCopy0 > math.MaxInt32 || scalingAdjustmentCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field ScalingAdjustment is of type int32")
					}
					scalingAdjustmentCopy := int32(scalingAdjustmentCopy0)
					f5f4elem.ScalingAdjustment = &scalingAdjustmentCopy
				}
				f5f4 = append(f5f4, *f5f4elem)
			}
			f5.StepAdjustments = f5f4
		}
		res.StepScalingPolicyConfiguration = f5
	}
	if r.ko.Spec.TargetTrackingScalingPolicyConfiguration != nil {
		f6 := &svcsdktypes.TargetTrackingScalingPolicyConfiguration{}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification != nil {
			f6f0 := &svcsdktypes.CustomizedMetricSpecification{}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Dimensions != nil {
				f6f0f0 := []svcsdktypes.MetricDimension{}
				for _, f6f0f0iter := range r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Dimensions {
					f6f0f0elem := &svcsdktypes.MetricDimension{}
					if f6f0f0iter.Name != nil {
						f6f0f0elem.Name = f6f0f0iter.Name
					}
					if f6f0f0iter.Value != nil {
						f6f0f0elem.Value = f6f0f0iter.Value
					}
					f6f0f0 = append(f6f0f0, *f6f0f0elem)
				}
				f6f0.Dimensions = f6f0f0
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.MetricName != nil {
				f6f0.MetricName = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.MetricName
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Namespace != nil {
				f6f0.Namespace = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Namespace
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Statistic != nil {
				f6f0.Statistic = svcsdktypes.MetricStatistic(*r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Statistic)
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Unit != nil {
				f6f0.Unit = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Unit
			}
			f6.CustomizedMetricSpecification = f6f0
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.DisableScaleIn != nil {
			f6.DisableScaleIn = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.DisableScaleIn
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification != nil {
			f6f2 := &svcsdktypes.PredefinedMetricSpecification{}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.PredefinedMetricType != nil {
				f6f2.PredefinedMetricType = svcsdktypes.MetricType(*r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.PredefinedMetricType)
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.ResourceLabel != nil {
				f6f2.ResourceLabel = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.ResourceLabel
			}
			f6.PredefinedMetricSpecification = f6f2
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown != nil {
			scaleInCooldownCopy0 := *r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown
			if scaleInCooldownCopy0 > math.MaxInt32 || scaleInCooldownCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ScaleInCooldown is of type int32")
			}
			scaleInCooldownCopy := int32(scaleInCooldownCopy0)
			f6.ScaleInCooldown = &scaleInCooldownCopy
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown != nil {
			scaleOutCooldownCopy0 := *r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown
			if scaleOutCooldownCopy0 > math.MaxInt32 || scaleOutCooldownCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ScaleOutCooldown is of type int32")
			}
			scaleOutCooldownCopy := int32(scaleOutCooldownCopy0)
			f6.ScaleOutCooldown = &scaleOutCooldownCopy
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.TargetValue != nil {
			f6.TargetValue = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.TargetValue
		}
		res.TargetTrackingScalingPolicyConfiguration = f6
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutScalingPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.PutScalingPolicy(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutScalingPolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Alarms != nil {
		f0 := []*svcapitypes.Alarm{}
		for _, f0iter := range resp.Alarms {
			f0elem := &svcapitypes.Alarm{}
			if f0iter.AlarmARN != nil {
				f0elem.AlarmARN = f0iter.AlarmARN
			}
			if f0iter.AlarmName != nil {
				f0elem.AlarmName = f0iter.AlarmName
			}
			f0 = append(f0, f0elem)
		}
		ko.Status.Alarms = f0
	} else {
		ko.Status.Alarms = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.PolicyARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.PolicyARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	rm.customSetLastModifiedTimeToCurrentTime(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.PutScalingPolicyInput, error) {
	res := &svcsdk.PutScalingPolicyInput{}

	if r.ko.Spec.PolicyName != nil {
		res.PolicyName = r.ko.Spec.PolicyName
	}
	if r.ko.Spec.PolicyType != nil {
		res.PolicyType = svcsdktypes.PolicyType(*r.ko.Spec.PolicyType)
	}
	if r.ko.Spec.ResourceID != nil {
		res.ResourceId = r.ko.Spec.ResourceID
	}
	if r.ko.Spec.ScalableDimension != nil {
		res.ScalableDimension = svcsdktypes.ScalableDimension(*r.ko.Spec.ScalableDimension)
	}
	if r.ko.Spec.ServiceNamespace != nil {
		res.ServiceNamespace = svcsdktypes.ServiceNamespace(*r.ko.Spec.ServiceNamespace)
	}
	if r.ko.Spec.StepScalingPolicyConfiguration != nil {
		f5 := &svcsdktypes.StepScalingPolicyConfiguration{}
		if r.ko.Spec.StepScalingPolicyConfiguration.AdjustmentType != nil {
			f5.AdjustmentType = svcsdktypes.AdjustmentType(*r.ko.Spec.StepScalingPolicyConfiguration.AdjustmentType)
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.Cooldown != nil {
			cooldownCopy0 := *r.ko.Spec.StepScalingPolicyConfiguration.Cooldown
			if cooldownCopy0 > math.MaxInt32 || cooldownCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field Cooldown is of type int32")
			}
			cooldownCopy := int32(cooldownCopy0)
			f5.Cooldown = &cooldownCopy
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.MetricAggregationType != nil {
			f5.MetricAggregationType = svcsdktypes.MetricAggregationType(*r.ko.Spec.StepScalingPolicyConfiguration.MetricAggregationType)
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.MinAdjustmentMagnitude != nil {
			minAdjustmentMagnitudeCopy0 := *r.ko.Spec.StepScalingPolicyConfiguration.MinAdjustmentMagnitude
			if minAdjustmentMagnitudeCopy0 > math.MaxInt32 || minAdjustmentMagnitudeCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field MinAdjustmentMagnitude is of type int32")
			}
			minAdjustmentMagnitudeCopy := int32(minAdjustmentMagnitudeCopy0)
			f5.MinAdjustmentMagnitude = &minAdjustmentMagnitudeCopy
		}
		if r.ko.Spec.StepScalingPolicyConfiguration.StepAdjustments != nil {
			f5f4 := []svcsdktypes.StepAdjustment{}
			for _, f5f4iter := range r.ko.Spec.StepScalingPolicyConfiguration.StepAdjustments {
				f5f4elem := &svcsdktypes.StepAdjustment{}
				if f5f4iter.MetricIntervalLowerBound != nil {
					f5f4elem.MetricIntervalLowerBound = f5f4iter.MetricIntervalLowerBound
				}
				if f5f4iter.MetricIntervalUpperBound != nil {
					f5f4elem.MetricIntervalUpperBound = f5f4iter.MetricIntervalUpperBound
				}
				if f5f4iter.ScalingAdjustment != nil {
					scalingAdjustmentCopy0 := *f5f4iter.ScalingAdjustment
					if scalingAdjustmentCopy0 > math.MaxInt32 || scalingAdjustmentCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field ScalingAdjustment is of type int32")
					}
					scalingAdjustmentCopy := int32(scalingAdjustmentCopy0)
					f5f4elem.ScalingAdjustment = &scalingAdjustmentCopy
				}
				f5f4 = append(f5f4, *f5f4elem)
			}
			f5.StepAdjustments = f5f4
		}
		res.StepScalingPolicyConfiguration = f5
	}
	if r.ko.Spec.TargetTrackingScalingPolicyConfiguration != nil {
		f6 := &svcsdktypes.TargetTrackingScalingPolicyConfiguration{}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification != nil {
			f6f0 := &svcsdktypes.CustomizedMetricSpecification{}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Dimensions != nil {
				f6f0f0 := []svcsdktypes.MetricDimension{}
				for _, f6f0f0iter := range r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Dimensions {
					f6f0f0elem := &svcsdktypes.MetricDimension{}
					if f6f0f0iter.Name != nil {
						f6f0f0elem.Name = f6f0f0iter.Name
					}
					if f6f0f0iter.Value != nil {
						f6f0f0elem.Value = f6f0f0iter.Value
					}
					f6f0f0 = append(f6f0f0, *f6f0f0elem)
				}
				f6f0.Dimensions = f6f0f0
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.MetricName != nil {
				f6f0.MetricName = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.MetricName
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Namespace != nil {
				f6f0.Namespace = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Namespace
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Statistic != nil {
				f6f0.Statistic = svcsdktypes.MetricStatistic(*r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Statistic)
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Unit != nil {
				f6f0.Unit = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.CustomizedMetricSpecification.Unit
			}
			f6.CustomizedMetricSpecification = f6f0
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.DisableScaleIn != nil {
			f6.DisableScaleIn = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.DisableScaleIn
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification != nil {
			f6f2 := &svcsdktypes.PredefinedMetricSpecification{}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.PredefinedMetricType != nil {
				f6f2.PredefinedMetricType = svcsdktypes.MetricType(*r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.PredefinedMetricType)
			}
			if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.ResourceLabel != nil {
				f6f2.ResourceLabel = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.PredefinedMetricSpecification.ResourceLabel
			}
			f6.PredefinedMetricSpecification = f6f2
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown != nil {
			scaleInCooldownCopy0 := *r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown
			if scaleInCooldownCopy0 > math.MaxInt32 || scaleInCooldownCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ScaleInCooldown is of type int32")
			}
			scaleInCooldownCopy := int32(scaleInCooldownCopy0)
			f6.ScaleInCooldown = &scaleInCooldownCopy
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown != nil {
			scaleOutCooldownCopy0 := *r.ko.Spec.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown
			if scaleOutCooldownCopy0 > math.MaxInt32 || scaleOutCooldownCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ScaleOutCooldown is of type int32")
			}
			scaleOutCooldownCopy := int32(scaleOutCooldownCopy0)
			f6.ScaleOutCooldown = &scaleOutCooldownCopy
		}
		if r.ko.Spec.TargetTrackingScalingPolicyConfiguration.TargetValue != nil {
			f6.TargetValue = r.ko.Spec.TargetTrackingScalingPolicyConfiguration.TargetValue
		}
		res.TargetTrackingScalingPolicyConfiguration = f6
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteScalingPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteScalingPolicy(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteScalingPolicy", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteScalingPolicyInput, error) {
	res := &svcsdk.DeleteScalingPolicyInput{}

	if r.ko.Spec.PolicyName != nil {
		res.PolicyName = r.ko.Spec.PolicyName
	}
	if r.ko.Spec.ResourceID != nil {
		res.ResourceId = r.ko.Spec.ResourceID
	}
	if r.ko.Spec.ScalableDimension != nil {
		res.ScalableDimension = svcsdktypes.ScalableDimension(*r.ko.Spec.ScalableDimension)
	}
	if r.ko.Spec.ServiceNamespace != nil {
		res.ServiceNamespace = svcsdktypes.ServiceNamespace(*r.ko.Spec.ServiceNamespace)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ScalingPolicy,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
