apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - common
resources:
  - bases/applicationautoscaling.services.k8s.aws_scalabletargets.yaml
  - bases/applicationautoscaling.services.k8s.aws_scalingpolicies.yaml
  - bases/applicationautoscaling.services.k8s.aws_scheduledactions.yaml
