apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/applicationautoscaling.services.k8s.aws_scalabletargets.yaml
  - bases/applicationautoscaling.services.k8s.aws_scalingpolicies.yaml
