// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Represents a CloudWatch alarm associated with a scaling policy.
type Alarm struct {
	AlarmARN  *string `json:"alarmARN,omitempty"`
	AlarmName *string `json:"alarmName,omitempty"`
}

// Represents a CloudWatch metric of your choosing for a target tracking scaling
// policy to use with Application Auto Scaling.
//
// For information about the available metrics for a service, see Amazon Web
// Services services that publish CloudWatch metrics (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html)
// in the Amazon CloudWatch User Guide.
//
// To create your customized metric specification:
//
//   - Add values for each required parameter from CloudWatch. You can use
//     an existing metric, or a new metric that you create. To use your own metric,
//     you must first publish the metric to CloudWatch. For more information,
//     see Publish custom metrics (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html)
//     in the Amazon CloudWatch User Guide.
//
//   - Choose a metric that changes proportionally with capacity. The value
//     of the metric should increase or decrease in inverse proportion to the
//     number of capacity units. That is, the value of the metric should decrease
//     when capacity increases, and increase when capacity decreases.
//
// For more information about the CloudWatch terminology below, see Amazon CloudWatch
// concepts (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html)
// in the Amazon CloudWatch User Guide.
type CustomizedMetricSpecification struct {
	Dimensions []*MetricDimension `json:"dimensions,omitempty"`
	MetricName *string            `json:"metricName,omitempty"`
	Namespace  *string            `json:"namespace,omitempty"`
	Statistic  *string            `json:"statistic,omitempty"`
	Unit       *string            `json:"unit,omitempty"`
}

// A GetPredictiveScalingForecast call returns the load forecast for a predictive
// scaling policy. This structure includes the data points for that load forecast,
// along with the timestamps of those data points and the metric specification.
type LoadForecast struct {
	// This structure specifies the metrics and target utilization settings for
	// a predictive scaling policy.
	//
	// You must specify either a metric pair, or a load metric and a scaling metric
	// individually. Specifying a metric pair instead of individual metrics provides
	// a simpler way to configure metrics for a scaling policy. You choose the metric
	// pair, and the policy automatically knows the correct sum and average statistics
	// to use for the load metric and the scaling metric.
	MetricSpecification *PredictiveScalingMetricSpecification `json:"metricSpecification,omitempty"`
}

// Describes the dimension names and values associated with a metric.
type MetricDimension struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Describes the reason for an activity that isn't scaled (not scaled activity),
// in machine-readable format. For help interpreting the not scaled reason details,
// see Scaling activities for Application Auto Scaling (https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-scaling-activities.html)
// in the Application Auto Scaling User Guide.
type NotScaledReason struct {
	Code            *string `json:"code,omitempty"`
	CurrentCapacity *int64  `json:"currentCapacity,omitempty"`
	MaxCapacity     *int64  `json:"maxCapacity,omitempty"`
	MinCapacity     *int64  `json:"minCapacity,omitempty"`
}

// Represents a predefined metric for a target tracking scaling policy to use
// with Application Auto Scaling.
//
// For more information, Predefined metrics for target tracking scaling policies
// (https://docs.aws.amazon.com/autoscaling/application/userguide/monitoring-cloudwatch.html#predefined-metrics)
// in the Application Auto Scaling User Guide.
type PredefinedMetricSpecification struct {
	PredefinedMetricType *string `json:"predefinedMetricType,omitempty"`
	ResourceLabel        *string `json:"resourceLabel,omitempty"`
}

// Represents a CloudWatch metric of your choosing for a predictive scaling
// policy.
type PredictiveScalingCustomizedMetricSpecification struct {
	MetricDataQueries []*PredictiveScalingMetricDataQuery `json:"metricDataQueries,omitempty"`
}

// Describes the scaling metric.
type PredictiveScalingMetric struct {
	Dimensions []*PredictiveScalingMetricDimension `json:"dimensions,omitempty"`
	MetricName *string                             `json:"metricName,omitempty"`
	Namespace  *string                             `json:"namespace,omitempty"`
}

// The metric data to return. Also defines whether this call is returning data
// for one metric only, or whether it is performing a math expression on the
// values of returned metric statistics to create a new time series. A time
// series is a series of data points, each of which is associated with a timestamp.
type PredictiveScalingMetricDataQuery struct {
	Expression *string `json:"expression,omitempty"`
	ID         *string `json:"id,omitempty"`
	Label      *string `json:"label,omitempty"`
	// This structure defines the CloudWatch metric to return, along with the statistic
	// and unit.
	MetricStat *PredictiveScalingMetricStat `json:"metricStat,omitempty"`
	ReturnData *bool                        `json:"returnData,omitempty"`
}

// Describes the dimension of a metric.
type PredictiveScalingMetricDimension struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// This structure specifies the metrics and target utilization settings for
// a predictive scaling policy.
//
// You must specify either a metric pair, or a load metric and a scaling metric
// individually. Specifying a metric pair instead of individual metrics provides
// a simpler way to configure metrics for a scaling policy. You choose the metric
// pair, and the policy automatically knows the correct sum and average statistics
// to use for the load metric and the scaling metric.
type PredictiveScalingMetricSpecification struct {
	// Represents a CloudWatch metric of your choosing for a predictive scaling
	// policy.
	CustomizedCapacityMetricSpecification *PredictiveScalingCustomizedMetricSpecification `json:"customizedCapacityMetricSpecification,omitempty"`
	// Represents a CloudWatch metric of your choosing for a predictive scaling
	// policy.
	CustomizedLoadMetricSpecification *PredictiveScalingCustomizedMetricSpecification `json:"customizedLoadMetricSpecification,omitempty"`
	// Represents a CloudWatch metric of your choosing for a predictive scaling
	// policy.
	CustomizedScalingMetricSpecification *PredictiveScalingCustomizedMetricSpecification `json:"customizedScalingMetricSpecification,omitempty"`
	// Describes a load metric for a predictive scaling policy.
	//
	// When returned in the output of DescribePolicies, it indicates that a predictive
	// scaling policy uses individually specified load and scaling metrics instead
	// of a metric pair.
	PredefinedLoadMetricSpecification *PredictiveScalingPredefinedLoadMetricSpecification `json:"predefinedLoadMetricSpecification,omitempty"`
	// Represents a metric pair for a predictive scaling policy.
	PredefinedMetricPairSpecification *PredictiveScalingPredefinedMetricPairSpecification `json:"predefinedMetricPairSpecification,omitempty"`
	// Describes a scaling metric for a predictive scaling policy.
	//
	// When returned in the output of DescribePolicies, it indicates that a predictive
	// scaling policy uses individually specified load and scaling metrics instead
	// of a metric pair.
	PredefinedScalingMetricSpecification *PredictiveScalingPredefinedScalingMetricSpecification `json:"predefinedScalingMetricSpecification,omitempty"`
	TargetValue                          *float64                                               `json:"targetValue,omitempty"`
}

// This structure defines the CloudWatch metric to return, along with the statistic
// and unit.
type PredictiveScalingMetricStat struct {
	// Describes the scaling metric.
	Metric *PredictiveScalingMetric `json:"metric,omitempty"`
	Stat   *string                  `json:"stat,omitempty"`
	Unit   *string                  `json:"unit,omitempty"`
}

// Represents a predictive scaling policy configuration.
type PredictiveScalingPolicyConfiguration struct {
	MaxCapacityBreachBehavior *string                                 `json:"maxCapacityBreachBehavior,omitempty"`
	MaxCapacityBuffer         *int64                                  `json:"maxCapacityBuffer,omitempty"`
	MetricSpecifications      []*PredictiveScalingMetricSpecification `json:"metricSpecifications,omitempty"`
	Mode                      *string                                 `json:"mode,omitempty"`
	SchedulingBufferTime      *int64                                  `json:"schedulingBufferTime,omitempty"`
}

// Describes a load metric for a predictive scaling policy.
//
// When returned in the output of DescribePolicies, it indicates that a predictive
// scaling policy uses individually specified load and scaling metrics instead
// of a metric pair.
type PredictiveScalingPredefinedLoadMetricSpecification struct {
	PredefinedMetricType *string `json:"predefinedMetricType,omitempty"`
	ResourceLabel        *string `json:"resourceLabel,omitempty"`
}

// Represents a metric pair for a predictive scaling policy.
type PredictiveScalingPredefinedMetricPairSpecification struct {
	PredefinedMetricType *string `json:"predefinedMetricType,omitempty"`
	ResourceLabel        *string `json:"resourceLabel,omitempty"`
}

// Describes a scaling metric for a predictive scaling policy.
//
// When returned in the output of DescribePolicies, it indicates that a predictive
// scaling policy uses individually specified load and scaling metrics instead
// of a metric pair.
type PredictiveScalingPredefinedScalingMetricSpecification struct {
	PredefinedMetricType *string `json:"predefinedMetricType,omitempty"`
	ResourceLabel        *string `json:"resourceLabel,omitempty"`
}

// Represents the minimum and maximum capacity for a scheduled action.
type ScalableTargetAction struct {
	MaxCapacity *int64 `json:"maxCapacity,omitempty"`
	MinCapacity *int64 `json:"minCapacity,omitempty"`
}

// Represents a scalable target.
type ScalableTarget_SDK struct {
	CreationTime      *metav1.Time `json:"creationTime,omitempty"`
	MaxCapacity       *int64       `json:"maxCapacity,omitempty"`
	MinCapacity       *int64       `json:"minCapacity,omitempty"`
	PredictedCapacity *int64       `json:"predictedCapacity,omitempty"`
	ResourceID        *string      `json:"resourceID,omitempty"`
	RoleARN           *string      `json:"roleARN,omitempty"`
	ScalableDimension *string      `json:"scalableDimension,omitempty"`
	ScalableTargetARN *string      `json:"scalableTargetARN,omitempty"`
	ServiceNamespace  *string      `json:"serviceNamespace,omitempty"`
	// Specifies whether the scaling activities for a scalable target are in a suspended
	// state.
	SuspendedState *SuspendedState `json:"suspendedState,omitempty"`
}

// Represents a scaling activity.
type ScalingActivity struct {
	ActivityID        *string      `json:"activityID,omitempty"`
	Cause             *string      `json:"cause,omitempty"`
	Description       *string      `json:"description,omitempty"`
	Details           *string      `json:"details,omitempty"`
	EndTime           *metav1.Time `json:"endTime,omitempty"`
	ResourceID        *string      `json:"resourceID,omitempty"`
	ScalableDimension *string      `json:"scalableDimension,omitempty"`
	ServiceNamespace  *string      `json:"serviceNamespace,omitempty"`
	StartTime         *metav1.Time `json:"startTime,omitempty"`
	StatusMessage     *string      `json:"statusMessage,omitempty"`
}

// Represents a scaling policy to use with Application Auto Scaling.
//
// For more information about configuring scaling policies for a specific service,
// see Amazon Web Services services that you can use with Application Auto Scaling
// (https://docs.aws.amazon.com/autoscaling/application/userguide/integrated-services-list.html)
// in the Application Auto Scaling User Guide.
type ScalingPolicy_SDK struct {
	Alarms       []*Alarm     `json:"alarms,omitempty"`
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	PolicyARN    *string      `json:"policyARN,omitempty"`
	PolicyName   *string      `json:"policyName,omitempty"`
	PolicyType   *string      `json:"policyType,omitempty"`
	// Represents a predictive scaling policy configuration.
	PredictiveScalingPolicyConfiguration *PredictiveScalingPolicyConfiguration `json:"predictiveScalingPolicyConfiguration,omitempty"`
	ResourceID                           *string                               `json:"resourceID,omitempty"`
	ScalableDimension                    *string                               `json:"scalableDimension,omitempty"`
	ServiceNamespace                     *string                               `json:"serviceNamespace,omitempty"`
	// Represents a step scaling policy configuration to use with Application Auto
	// Scaling.
	//
	// For more information, see Step scaling policies (https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-step-scaling-policies.html)
	// in the Application Auto Scaling User Guide.
	StepScalingPolicyConfiguration *StepScalingPolicyConfiguration `json:"stepScalingPolicyConfiguration,omitempty"`
	// Represents a target tracking scaling policy configuration to use with Application
	// Auto Scaling.
	//
	// For more information, see Target tracking scaling policies (https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking.html)
	// in the Application Auto Scaling User Guide.
	TargetTrackingScalingPolicyConfiguration *TargetTrackingScalingPolicyConfiguration `json:"targetTrackingScalingPolicyConfiguration,omitempty"`
}

// Represents a scheduled action.
type ScheduledAction struct {
	CreationTime       *metav1.Time `json:"creationTime,omitempty"`
	EndTime            *metav1.Time `json:"endTime,omitempty"`
	ResourceID         *string      `json:"resourceID,omitempty"`
	ScalableDimension  *string      `json:"scalableDimension,omitempty"`
	Schedule           *string      `json:"schedule,omitempty"`
	ScheduledActionARN *string      `json:"scheduledActionARN,omitempty"`
	ServiceNamespace   *string      `json:"serviceNamespace,omitempty"`
	StartTime          *metav1.Time `json:"startTime,omitempty"`
	Timezone           *string      `json:"timezone,omitempty"`
}

// Represents a step adjustment for a StepScalingPolicyConfiguration (https://docs.aws.amazon.com/autoscaling/application/APIReference/API_StepScalingPolicyConfiguration.html).
// Describes an adjustment based on the difference between the value of the
// aggregated CloudWatch metric and the breach threshold that you've defined
// for the alarm.
//
// For the following examples, suppose that you have an alarm with a breach
// threshold of 50:
//
//   - To initiate the adjustment when the metric is greater than or equal
//     to 50 and less than 60, specify a lower bound of 0 and an upper bound
//     of 10.
//
//   - To initiate the adjustment when the metric is greater than 40 and less
//     than or equal to 50, specify a lower bound of -10 and an upper bound of
//     0.
//
// There are a few rules for the step adjustments for your step policy:
//
//   - The ranges of your step adjustments can't overlap or have a gap.
//
//   - At most one step adjustment can have a null lower bound. If one step
//     adjustment has a negative lower bound, then there must be a step adjustment
//     with a null lower bound.
//
//   - At most one step adjustment can have a null upper bound. If one step
//     adjustment has a positive upper bound, then there must be a step adjustment
//     with a null upper bound.
//
//   - The upper and lower bound can't be null in the same step adjustment.
type StepAdjustment struct {
	MetricIntervalLowerBound *float64 `json:"metricIntervalLowerBound,omitempty"`
	MetricIntervalUpperBound *float64 `json:"metricIntervalUpperBound,omitempty"`
	ScalingAdjustment        *int64   `json:"scalingAdjustment,omitempty"`
}

// Represents a step scaling policy configuration to use with Application Auto
// Scaling.
//
// For more information, see Step scaling policies (https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-step-scaling-policies.html)
// in the Application Auto Scaling User Guide.
type StepScalingPolicyConfiguration struct {
	AdjustmentType         *string           `json:"adjustmentType,omitempty"`
	Cooldown               *int64            `json:"cooldown,omitempty"`
	MetricAggregationType  *string           `json:"metricAggregationType,omitempty"`
	MinAdjustmentMagnitude *int64            `json:"minAdjustmentMagnitude,omitempty"`
	StepAdjustments        []*StepAdjustment `json:"stepAdjustments,omitempty"`
}

// Specifies whether the scaling activities for a scalable target are in a suspended
// state.
type SuspendedState struct {
	DynamicScalingInSuspended  *bool `json:"dynamicScalingInSuspended,omitempty"`
	DynamicScalingOutSuspended *bool `json:"dynamicScalingOutSuspended,omitempty"`
	ScheduledScalingSuspended  *bool `json:"scheduledScalingSuspended,omitempty"`
}

// The metric data to return. Also defines whether this call is returning data
// for one metric only, or whether it is performing a math expression on the
// values of returned metric statistics to create a new time series. A time
// series is a series of data points, each of which is associated with a timestamp.
//
// For more information and examples, see Create a target tracking scaling policy
// for Application Auto Scaling using metric math (https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking-metric-math.html)
// in the Application Auto Scaling User Guide.
type TargetTrackingMetricDataQuery struct {
	Expression *string `json:"expression,omitempty"`
	ID         *string `json:"id,omitempty"`
	Label      *string `json:"label,omitempty"`
	ReturnData *bool   `json:"returnData,omitempty"`
}

// This structure defines the CloudWatch metric to return, along with the statistic
// and unit.
//
// For more information about the CloudWatch terminology below, see Amazon CloudWatch
// concepts (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html)
// in the Amazon CloudWatch User Guide.
type TargetTrackingMetricStat struct {
	Stat *string `json:"stat,omitempty"`
}

// Represents a target tracking scaling policy configuration to use with Application
// Auto Scaling.
//
// For more information, see Target tracking scaling policies (https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking.html)
// in the Application Auto Scaling User Guide.
type TargetTrackingScalingPolicyConfiguration struct {
	// Represents a CloudWatch metric of your choosing for a target tracking scaling
	// policy to use with Application Auto Scaling.
	//
	// For information about the available metrics for a service, see Amazon Web
	// Services services that publish CloudWatch metrics (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html)
	// in the Amazon CloudWatch User Guide.
	//
	// To create your customized metric specification:
	//
	//    * Add values for each required parameter from CloudWatch. You can use
	//    an existing metric, or a new metric that you create. To use your own metric,
	//    you must first publish the metric to CloudWatch. For more information,
	//    see Publish custom metrics (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html)
	//    in the Amazon CloudWatch User Guide.
	//
	//    * Choose a metric that changes proportionally with capacity. The value
	//    of the metric should increase or decrease in inverse proportion to the
	//    number of capacity units. That is, the value of the metric should decrease
	//    when capacity increases, and increase when capacity decreases.
	//
	// For more information about the CloudWatch terminology below, see Amazon CloudWatch
	// concepts (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html)
	// in the Amazon CloudWatch User Guide.
	CustomizedMetricSpecification *CustomizedMetricSpecification `json:"customizedMetricSpecification,omitempty"`
	DisableScaleIn                *bool                          `json:"disableScaleIn,omitempty"`
	// Represents a predefined metric for a target tracking scaling policy to use
	// with Application Auto Scaling.
	//
	// For more information, Predefined metrics for target tracking scaling policies
	// (https://docs.aws.amazon.com/autoscaling/application/userguide/monitoring-cloudwatch.html#predefined-metrics)
	// in the Application Auto Scaling User Guide.
	PredefinedMetricSpecification *PredefinedMetricSpecification `json:"predefinedMetricSpecification,omitempty"`
	ScaleInCooldown               *int64                         `json:"scaleInCooldown,omitempty"`
	ScaleOutCooldown              *int64                         `json:"scaleOutCooldown,omitempty"`
	TargetValue                   *float64                       `json:"targetValue,omitempty"`
}
